charity/models/categorie.py
from extensions import db

class Categorie(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    libelle = db.Column(db.String(255), nullable=False)
    description = db.Column(db.String(255), nullable=True)

charity/models/don.py
from extensions import db

class Don(db.Model):
    __tablename__ = 'dons'
    id = db.Column(db.Integer, primary_key = True)
    montant = db.Column(db.Float, nullable=False)
    identifiant = db.Column(db.String(255), nullable=False)
    telephone = db.Column(db.String(10), nullable=False)
    modePayement = db.Column(db.String(10), nullable=False)
    projet_id = db.Column(db.Integer, db.ForeignKey('projet.id'), nullable=False)
    projet = db.relationship('Projet', backref=db.backref('dons', lazy=True))
    

charity/models/projet.py
from extensions import db
import os
from werkzeug.utils import secure_filename

upload_folder = 'charity/static/image'
os.makedirs(upload_folder, exist_ok=True)

class Projet(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    libelle = db.Column(db.String(255), nullable=False)
    description = db.Column(db.String(255), nullable=False)
    image = db.Column(db.String(255), nullable=False)
    categorie_id = db.Column(db.Integer, db.ForeignKey('categorie.id'), nullable=False)
    categorie = db.relationship('Categorie', backref=db.backref('projet', lazy=True))

    def save_image(self, image_file):
        if image_file:
            filename = secure_filename(image_file.filename)
            image_path = os.path.join(upload_folder, filename)
            image_file.save(image_path)
            self.image = filename
            db.session.commit()

charity/__init__.py
from flask import Blueprint

web_charity_bp = Blueprint('charity_web', __name__, template_folder='templates', static_folder='static')

api_charity_bp = Blueprint('charity_api', __name__, template_folder='templates', static_folder='static')

from charity.views import route, api_route

charity/controllers/CategorieController.py
from charity.models.categorie import Categorie
from flask import jsonify, request
from extensions import db

class CategorieController:

    def __init__(self):
        self.categorie_model = Categorie

    def create(self):
        try:
            data = request.get_json()
            nouvelle_categorie = self.categorie_model(libelle=data['libelle'])
            db.session.add(nouvelle_categorie)
            db.session.commit()
            return jsonify({'message': 'Nouvelle catégorie créée avec succès'}), 201
        except KeyError:
            return jsonify({'message': 'Données manquantes'}), 400
        except Exception as e:
            db.session.rollback()
            return jsonify({'message': e}), 500
        
    def all(self):
        try:
            categories = self.categorie_model.query.all()
            result = [{'id': categorie.id, 'libelle': categorie.libelle} for categorie in categories]
            return jsonify(result), 200
        except Exception as e:
            return jsonify({'message': e}), 500

charity/controllers/ProjetController.py
from charity.models.projet import Projet
from flask import jsonify, request
from extensions import db

class ProjetController:

    def __init__(self):
        self.project_model = Projet
        
    def all(self):
        try:
            projets = self.project_model.query.all()
            result = [{'id': projet.id, 'libelle': projet.libelle, 'image': projet.image} for projet in projets]
            return jsonify(result), 200
        except Exception as e:
            return jsonify({'message': e}), 500
        
    def create(self):
        try:
            libelle = request.form['libelle']
            categorie_id = request.form['categorie_id']
            description = request.form['description']

            if 'image' not in request.files:
                return jsonify({'message': 'Aucun fichier image'}), 400
            
            image = request.files['image']
            projet = self.project_model(libelle=libelle, description=description,
                                         categorie_id=categorie_id)
            projet.save_image(image)

            db.session.add(projet)
            db.session.commit()

            return jsonify({'message': 'Projet créé avec succès'}), 201
        except KeyError:
            db.session.rollback()
            return jsonify({'message': 'Donnée manquant'}), 400
        except Exception as e:
            db.session.rollback()
            return jsonify({'message': e}), 500

    

charity/views/api_route.py
from flask import Blueprint, jsonify
from charity.data import projets
from charity import api_charity_bp
from charity.controllers.CategorieController import CategorieController
from charity.controllers.ProjetController import ProjetController

categorie_controller = CategorieController()
projet_controller = ProjetController()

@api_charity_bp.route("")
def api_list():
    return jsonify(projets)

@api_charity_bp.route("/categories", methods=['POST'])
def add_category():
    return categorie_controller.create()

@api_charity_bp.route("/categories", methods=['GET'])
def list_categories():
    return categorie_controller.all()

@api_charity_bp.route("/projets", methods=['POST'])
def add_projet():
    return projet_controller.create()

@api_charity_bp.route("/projets", methods=['GET'])
def list_projet():
    return projet_controller.all()

charity/views/route.py
from flask import render_template, Blueprint, request, redirect, url_for, flash, jsonify
#from charity.data import projets
from charity import web_charity_bp
from charity.models.projet import Projet
from charity.models.don import Don
import requests
from extensions import db

@web_charity_bp.route("/")
def index():
    projets = Projet.query.all()
    return render_template('index.html', projets = projets)

@web_charity_bp.route("/projet/<int:projet_id>")
def show(projet_id):
    projet = Projet.query.get_or_404(projet_id)
    total_dons = calculer_total_dons(projet_id)
    return render_template('show.html', projet=projet, total_dons=total_dons)

def calculer_total_dons(projet_id):
    projet = Projet.query.get_or_404(projet_id)
    dons = projet.dons
    total_dons = 0
    for don in dons:
        total_dons += don.montant

    return total_dons


@web_charity_bp.route("/don", methods=['POST'])
def don():
    try:
        identifiant = request.form['identifiant']
        montant = request.form['montant']
        telephone = request.form['telephone']
        modePayement = request.form['modePayement']
        projet_id = request.form['projet_id']

        don = Don(identifiant=identifiant,
                montant=montant,
                telephone=telephone,
                modePayement=modePayement,
                projet_id=projet_id)
        
        paygate_url ="https://paygateglobal.com/api/v1/pay"
        response = requests.post(paygate_url,
                                json={
                                    'auth_token': '5b2a5ed8-7764-4f51-a0fc-f3f49980d54e',
                                    'phone_number': telephone,
                                    'amount': montant,
                                    'identifiant': identifiant,
                                    'network': modePayement
                                })
        response_data = response.json()
        print('reponse', response_data)

        db.session.add(don)
        db.session.commit()

        total_dons = calculer_total_dons(projet_id)
        #flash('Merci pour votre don.', 'success')
        #return redirect(url_for('charity_web.show', projet_id=projet_id))

        return jsonify({'success': True, 'total_dons': total_dons})
    except Exception as e:
        print(e)
        #flash('Votre don a échoué .', 'error')
        #return redirect(url_for('charity_web.show', projet_id=projet_id))
        return jsonify({'success': False})

charity/templates/index.html
{% extends "layout.html" %}

{% block content %}
<div class="row">
    {% for projet in projets %} 
    <div class="col-md-4 mb-4">
        <div class="card rounded">
            <img src="{{ url_for('charity_web.static', filename='charity_img/' + projet.image) }}" class="card-img-top"
                alt="{{ projet.libelle }}">
            <div class="card-body">
                <h5 class="card-title">
                    <a href="{{url_for('charity_web.show', projet_id=projet.id)}}">{{ projet.libelle }}</a>
                    </h5>
                <p class="card-text">{{ projet.description }}</p> 
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

charity/templates/layout.html
<!doctype html>
<html>
  <head>
    {% block head %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <title>{% block title %}{% endblock %} - My Webpage</title>
    {% endblock %}
  </head>
  <body>
    
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="#">Charity</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{{url_for('charity_web.index')}}">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('charity_web.index')}}">Greating</a>
          </li>
          <!-- Add more navigation links here -->
          {% if current_user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="#">{{ current_user.username}}</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{url_for('auth.logout')}}">Deconnexion</a>
            </li>
          {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{{url_for('auth.login')}}">Login</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{url_for('auth.register')}}">Register</a>
            </li>
          {% endif %}
        </ul>
      </div>
    </nav>

    <div class="container mt-4">
      <div id="flash-message">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
        <ul class="list">
          {% for message in messages %}
            <li class="alert alert info" role="alert"> {{ message }}</li>
          {% endfor %}
        </ul> 
        {% endif %}
        {% endwith %}
      </div>

      <div id="content">{% block content %}{% endblock %}</div>
    </div>

    <footer class="footer bg-dark text-light mt-4 py-3">
      <div class="container">
        {% block footer %}
        &copy; 2024 Your Company
        {% endblock %}
      </div>
    </footer>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js" integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
    <script>
      $(document).ready(function(){
        $('#loading').hide();
        $('#form-don').submit(function(event){
          
        $('#loading').show();
          event.preventDefault();
          var form_data = $(this).serialize();
          $.ajax({
            type: 'POST',
            url: $(this).attr('action'),
            data: form_data,
            success: function(response) {
              if (response.success) {
                $('#flash-message').empty();
                $('#total_dons').text(response.total_dons);
                $('#modal-don').modal('hide');
                $('#flash-message').append('<li class="alert alert info" role="alert"> Merci pour votre don</li>')
              } else {
                console.log('error');
                $('#modal-don').modal('hide');
                $('#flash-message').append('<li class="alert alert danger" role="alert"> Votre don n\'a pas abouti!</li>')
              }
            },
            error: function() {
                console.log('error');
                $('#modal-don').modal('hide');
                $('#flash-message').append('<li class="alert alert danger" role="alert"> Votre don n\'a pas abouti!</li>')
            },
            complete: function() {
              $('#loading').hide();
            }
          })
        })
      })
    </script>
  </body>
</html>

charity/templates/show.html
{% extends "layout.html" %}

{% block content %}
<div class="media">
    <img class="align-self-center mr-3" src="{{ url_for('charity_web.static', filename='charity_img/' + projet.image) }}"
        alt="{{ projet.libelle }}">
    <div class="media-body">
        <h1 class="mt-0">{{ projet.libelle }}</h1>
        <p>{{ projet.categorie.libelle }}</p>
        <p> Montant : <span id="total_dons">{{ total_dons }}</span> FCFA</p>
        <p class="mb-0">
            <button type="button" class="btn btn-success" data-bs-toggle="modal" data-bs-target="#modal-don">
                Faire un don
            </button>
        </p>
    </div>
</div>



<div class="modal fade" id="modal-don" tabindex="-1" role="dialog" aria-labelledby="modal-don-title" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="staticBackdropLabel">Modal title</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <form class="row g-3" id="form-don" action="{{ url_for('charity_web.don') }}" method="post">
            
            <input class="form-control" name="projet_id" value="{{projet.id}}" hidden>
            <div class="col-md-6">
              <label for="identifiant" class="form-label">Un nom</label>
              <input type="text" class="form-control" name="identifiant" id="identifiant" placeholder="identifiant">
            </div>
            <div class="col-md-6">
              <label for="montant" class="form-label">Montant du don</label>
              <input type="number" class="form-control" name="montant" id="montant" placeholder="montant">
            </div>
            <div class="col-12">
              <label for="telephone" class="form-label">Telephone</label>
              <input type="tel" class="form-control" name="telephone" id="telephone" placeholder="Numero de mobile money">
            </div>
            <div class="col-md-6">
              <div class="form-check">
                <input class="form-check-input" type="radio" name="modePayement" id="modePayement1" value="TMONEY" checked>
                <label class="form-check-label" for="modePayement1">
                  Tmoney
                </label>
              </div>        
            </div>
            <div class="col-md-6">
              <div class="form-check">
                <input class="form-check-input" type="radio" name="modePayement" id="modePayement2" value="FLOOZ">
                <label class="form-check-label" for="modePayement2">
                  Moov
                </label>
              </div>        
            </div>
            <div class="col-12 mt-3">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
              <button type="submit" class="btn btn-primary">Valider</button>

              <div id="loading" class="text-danger">En cours...</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>

{% endblock %}